/* Generated By:JJTree: Do not edit this line. ASTExpression.java */

package org.codehaus.aspectwerkz.expression.ast;

public class ASTExpression extends SimpleNode {
    public ASTExpression(int id) {
        super(id);
    }

    public ASTExpression(ExpressionParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}