/* Generated By:JJTree: Do not edit this line. ASTGet.java */

package org.codehaus.aspectwerkz.expression.ast;

public class ASTGet extends SimpleNode {
    public ASTGet(int id) {
        super(id);
    }

    public ASTGet(ExpressionParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}