/* Generated By:JJTree: Do not edit this line. ASTHasMethod.java */

package org.codehaus.aspectwerkz.expression.ast;

public class ASTHasMethod extends SimpleNode {
    public ASTHasMethod(int id) {
        super(id);
    }

    public ASTHasMethod(ExpressionParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
