/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_codehaus_aspectwerkz_extension_hotswap_HotSwapClient */

#ifndef _Included_org_codehaus_aspectwerkz_extension_hotswap_HotSwapClient
#define _Included_org_codehaus_aspectwerkz_extension_hotswap_HotSwapClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_codehaus_aspectwerkz_extension_hotswap_HotSwapClient
 * Method:    hotswap
 * Signature: (Ljava/lang/String;Ljava/lang/Class;[BI)I
 */
JNIEXPORT jint JNICALL Java_org_codehaus_aspectwerkz_extension_hotswap_HotSwapClient_hotswap
  (JNIEnv *, jclass, jstring, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
